name = "tabplugins-site"
compatibility_date = "2026-10-09"
workers_dev = false
routes = [{ pattern = "tabplugins.top", custom_domain = true }, { pattern = "www.tabplugins.top", custom_domain = true }]
[assets]
directory = "./public"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
